# -----------------------------------------------------------
#  MKernel - Main Configuration
# -----------------------------------------------------------

modules:
  core:
    enabled: true
    commands:
      disposal: true
      globalchest: true
      payxp: true
      sendcoords: true
      nick: true

  admin:
    enabled: true
    chat: true
    commands:
      specialItem: true
      invsee: true
      gma: true
      gmsp: true
      gmc: true
      gms: true
      heal: true
      opme: true
      deopme: true
      spy: true
      vanish: true
      sequence: true
      flyspeed: true
      freeze: true

  chat:
    enabled: true
    format: true
    mentions: true
    roleplay: true
    endermanAnger: true

  shop:
    enabled: true

  teleport:
    enabled: true
    spawnAtLobby: true

  player:
    enabled: true
    joinTitle: true
    leaveTitle: true
    deathTitle: true
    recoverInventory: true

  world:
    enabled: true
    harvestRightClick: true
    autoItemRefill: true
    noNetherPortals: true
    timeWeatherControl: true

settings:
  permissions:
    chatFormat: "mkernel.events.chatformat"
    adminChat: "mkernel.events.adminchat"
    mentions: "mkernel.events.mentions"

  shops:
    taxPercent: 21.0
    serverAccount: "Hacienda"
    permissions:
      admin: "mkernel.shop.admin"

  teleport:
    tpCooldown: "5m"
    maxWarps: 3

  death:
    xpLossOnDeath: 0.7
    recoverInventory:
      requiredLevel: 10
      playerRadius: 10
      spawnDistance: 150

  chat:
    prefix: "<color:#d30000><bold>mkernel</bold> <white>»</white></color>"
    publicFormat: "%vault_prefix% <white>%mkernel_nick%</white> <aqua>»</aqua> <reset><message>"
    mentionsFormat: "<color:#d30000><bold>@<player>"
    permissions:
      format: "mkernel.events.chatformat"
      mentions: "mkernel.events.mentions"
    adminChat:
      trigger: "#"
      format: "<color:#d30000><bold>AdminChat</bold> <white>%mkernel_nick%</white> <light_purple>»</light_purple> <reset><message>"
      permission: "mkernel.events.adminchat"

  worlds:
    lobby:
      name: "lobby"
      coords:
        x: 0.5
        y: 65.0
        z: 0.5
        yaw: 180.0
        pitch: 0.0

  startupCommands:
    onServerLoad: []
    onWorldLoad: []
    onWorldUnload: []

  sequentialCommands:
    _example:
      - command: "say example"
        delay: 0
      - command: "say delay"
        delay: 2

blacklist:
  nicks: []
  commands:
    - /minecraft:me
  recipes: []

file-version: 2