# -----------------------------------------------------------
#  MKernel - Miarmacraft Configuration
# -----------------------------------------------------------

modules:
  dictatorship:
    enabled: true
    tithe: true
    fines: true

  blindGod:
    enabled: true

settings:
  permissions:

  blindGod:
    yThreshold: -20
    first: 50
    second: 100
    third: 150

  tithe:
    interval: "7d"
    amount: 100
    punishmentCommand: "sequence tithe_punishment <player>"

  fines:
    author: "Ministerio de la Verdad"
    expirationTime: "3d"
    punishmentCommand: "sequence fine_punishment <player>"
    bookFormat:
      title: "<red><bold>SANCIÓN MONETARIA</bold></red>"
      pages:
        - "<black><b>MULTA Nº:</b> #<id>\n\n<b>Infractor:</b> <player>\n<b>Motivo:</b> <reason>\n<b>Importe:</b> <amount> <dark_green>♦</dark_green>\n\n<b>Caduca:</b> <date>\n\n<dark_red>Deberás entregar este documento junto con el pago en el ayuntamiento</dark_red>"

file-version: 2