# -----------------------------------------------------------
#  MKernel - Miarmacraft Configuration
# -----------------------------------------------------------

modules:
  blindGod:
    enabled: true

  lawEnforcement:
    enabled: true
    townProtection:
      explosions: false

  shit:
    enabled: true

  piglinCartel:
    enabled: true

settings:
  permissions:

  blindGod:
    yThreshold: -20
    first: 50
    second: 100
    third: 150

  lawEnforcement:
    region: "hispania"
    aggroTimeSeconds: 30
    despawnTimeSeconds: 45
    spawnDelaySeconds: 3
    maxGolems: 6
    golemBaseLevel: 20
    golemLevelMultiplier: 1.12
    buildPerm: "mkernel.miarmacraft.town.build"
    usePerm: "mkernel.miarmacraft.town.use"
    harmAnimalsPerm: "mkernel.miarmacraft.town.harm"
    tempBanDuration: "48h"
    explosionsEnabled: false

  paysheet:
    tcpPercent: 15.0

  piglinCartel:
    taxAmount: 5
    currency: GOLD_INGOT

file-version: 4